---
title: "Inference for Comparing Two Samples"
author: "ENGEN102-23B (HAM) & (SEC) - Engineering Maths and Modelling 1B"
format:
  revealjs: 
    slide-number: c/t
    progress: true
    auto-stretch: false
    height: 1080
    width: 1920
    theme: reveal-extra/quartz.scss
    template-partials:
      - reveal-extra/title-block.html
    highlight-style: ayu
    code-line-numbers: false
    embed-resources: true
editor: source
---

## Statistical Inference for Two Samples {.margin-bottom}


Let’s consider the scenario where we measured the same numeric variable for two independent groups

. . .

An intuitive action would be to compare them, but what determines if they are distinct? 

. . .

One approach would be to identify whether it is plausible that the underlying mean of each group is the same

. . .

And it turns out we can adapt the framework for inference about one underlying mean for the difference between two underlying means

## The hypothesis statements

For a hypothesis test on $\mu_1 - \mu_2$, the set of hypothesis statements are:

$$
\begin{aligned}
  H_0\!: \mu_1 - \mu_2 = \text{Diff}_0 \\
  H_1\!: \mu_1 - \mu_2 \neq \text{Diff}_0
\end{aligned}
$$

The alternative hypothesis, $H_1$, can use any of the following: $\neq$, $>$, or $<$

## [Definition:]{style="color: darkorange;"} The test statistic for *&mu;*~1~ &minus; *&mu;*~2~

::: {.definition style="width: 40%;"}
$$
t_0 = \frac{(\bar{x}_1 - \bar{x}_2)- \text{Diff}_0}{\text{se}(\bar{x}_1 - \bar{x}_2)}
$$
:::

. . .

where:

::: {.incremental style="font-size: 0.9em; margin-top: -0.25em;"}
- $t_0$ is the *T*-test statistic (for $\mu_1 - \mu_2$)
- $\bar{x}_1$ is the **sample** mean of the first group
- $\bar{x}_2$ is the **sample** mean of the second group
- $\text{Diff}_0$ is the **hypothesised** difference between the *underlying* means $\mu_1 - \mu_2$
- $\text{se}(\bar{x})$ is the **standard error** of $\bar{x}_1 - \bar{x}_2$
:::

## *Briefly:* Calculation of the *p*-value

Let $T \rightarrow_D \text{Student}(\nu = \min(n_1-1,n_2-1))$, where:

::: {.tightList style="font-size: 0.9em;"}
- $\nu$ is the Student’s *t*-distribution’s degrees of freedom parameter
- $n_1$ and $n_2$ are the sample sizes of the first and second groups, respectively
- $t_0$ is the *T*-test statistic
:::

::::: {.columns style="font-size: 0.75em;"}
:::: {.column .fragment width="46%"}
::: {.definition}
If it is a two-sided test, e.g. [$H_1 \! : \mu_1 - \mu_2 \neq \text{Diff}_0$]{style="font-size: 0.9em"}

$\quad p\text{-value} = 2 \times \mathbb{P}(T > |t_0|)$
:::

:::: {style="margin-top: 25px;"}
::: {.definition-orchid .fragment}
If it is a one-sided test and [$H_1 \! : \mu_1 - \mu_2 > \text{Diff}_0$]{style="font-size: 0.9em"}

$\quad p\text{-value} = \mathbb{P}(T > t_0)$
:::
::::

:::: {style="margin-top: 25px;"}
::: {.definition-teal .fragment}
If it is a one-sided test and [$H_1 \! : \mu_1 - \mu_2 < \text{Diff}_0$]{style="font-size: 0.9em"}

$\quad p\text{-value} = \mathbb{P}(T < t_0)$
:::
::::
::::
:::::

::: {.aside}
The random variable $T$ is an approximation of all potential $t_0$ you could observe if the $\mu_1 - \mu_2 = \text{Diff}_0$ is indeed true
:::

## [Ex 7:]{style='color: tomato;'} Loads of Concrete Beams

> An experiment was conducted to estimate the difference in the underlying mean load of concrete beams that were reinforced with two different composite orthogonal grids: carbon or fibreglass.
$$
\begin{aligned}
\bar{x}_\text{C} = 42.8 ~ \text{kN}, \quad\quad s_\text{C} = 4.3 ~ \text{kN}, \quad\quad n_\text{C} = 26 \\ 
\bar{x}_\text{F} = 33.4 ~ \text{kN}, \quad\quad s_\text{F} = 2.2 ~ \text{kN}, \quad\quad n_\text{F} = 26
\end{aligned}
$$
Does the data strongly suggest that the underlying average load for the carbon beams is more than that for fibreglass beams? Either construct an appropriate 95% confidence interval or conduct an appropriate hypothesis test at the 5% level to answer this question, then interpret the output.

. . .

::: {style="width: 55%; margin-top: 25px;"}
```{python}
#| echo: true
# A Python script to print the exact value of the t-multiplier
from scipy.stats import t
t.ppf(0.975, df=25)
```
:::

::: {.aside}
Based on research by Smart, C. W., & Jensen, D. W. (1997). Flexure of Concrete Beams Reinforced with Advanced Composite Orthogrids. *Journal of Aerospace Engineering* **10**, 7--15.
:::

## Assumptions for inference on *&mu;*~1~ &minus; *&mu;*~2~

::: {.incremental}
1. **Independent** observations between *and* within groups
2. *Within* [group]{style="color: steelblue;"}: One measure of centre can satisfactorily summarise the group
3. *Within* [group]{style="color: steelblue;"}: Approximately symmetrical about the group's **sample mean**, $\bar{x}_i$, and there are no outliers
:::

. . .

::: {style="border-bottom: 5px solid orange; width: 12.5%;"}
More on **3.**
:::

Like the [assumptions for inference on [&mu;]{style="font-style: italic;"}]{style="color: orchid !important;"}, we are more lenient about this assumption with larger $n$
