---
title: "Textbook Reference"
format: html
bibliography: references.bib
embed-resources: true
toc: true
toc-depth: 3
toc-title: ""
page-layout: full
engine: knitr
---

```{css, echo = FALSE}
.ch-0 {
  margin-left: -0.75ch;
}
```

## Preface

The following topics from @bird21 _**Section M:** Statistics and probability_ are covered as part of the statistics component of ENGEN102.

- *Mean, median, mode and standard deviation* (pg. 743--750)
- *Probability* (pg. 751--763)
- *The Normal distribution* (pg. 771--779)
- *Sampling and estimation theories* (pg. 792--804)
- *Significance testing* (pg. 805--821)

The following topics from @stroud13 are covered as part of the statistics component of ENGEN102.

- *Data handling and statistics* (pg. 1045--1075)
- *Probability* (pg. 1076--1116)

The following topics from @lock21 _**Unit C:** Inference with Normal and t-Distributions_ are covered as part of the statistics component of ENGEN102.

- *Inference for a Mean* (pg. 448--469)
- *Inference for a Difference in Means* (pg. 485--501)

::: {.callout-warning appearance="simple"}
This is not an exhaustive list of all topics covered in the statistics component of ENGEN102.
:::

## Relevant Practice from @bird21

::: {.callout-tip appearance="simple"}
Some *t*-multipliers you may require that are not provided by @bird21 are:

- *t*^\*^~[0.98]{.ch-0}~(*&nu;* = 5) = 2.76
- *t*^\*^~[0.9875]{.ch-0}~(*&nu;* = 9) = 2.69
- *t*^\*^~[0.85]{.ch-0}~(*&nu;* = 11) = 1.09
- *t*^\*^~[0.01]{.ch-0}~(*&nu;* = 39) = -2.43
- *t*^\*^~[0.05]{.ch-0}~(*&nu;* = 39) = -1.68
- *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 39) = 1.68
- *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 39) = 2.02
- *t*^\*^~[0.99]{.ch-0}~(*&nu;* = 39) = 2.43
- *t*^\*^~[0.995]{.ch-0}~(*&nu;* = 39) = 2.71
- *t*^\*^~[0.01]{.ch-0}~(*&nu;* = 49) = -2.40
- *t*^\*^~[0.05]{.ch-0}~(*&nu;* = 49) = -1.68
- *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 49) = 1.68
- *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 49) = 2.01
- *t*^\*^~[0.99]{.ch-0}~(*&nu;* = 49) = 2.40
- *t*^\*^~[0.995]{.ch-0}~(*&nu;* = 49) = 2.68
- *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 59) = 2.00
- *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 79) = 1.66
:::

### Worked Problems

The following lists which worked problems from @bird21 that are relevant to the statistics component of ENGEN102.

- *Mean, median, mode and standard deviation*: Problems 1, 2, and 5
- *Probability*: Problems 1 and 6(a)
- *The Normal distribution*: Problems 1--4
- *Sampling and estimation theories*: Problems 2(a), 9, 11
- *Significance testing*: Problems 5, 6, 8, 9 and 10

### Revision Test Questions

The following lists which questions from the @bird21 revision tests that are relevant to the statistics component of ENGEN102.

- Revision Test 18: Questions 3, 6(a), and 6(c)
- Revision Test 19: Questions 3 and 4
- Revision Test 20: Questions 2, 4, 5, 6(a), and 6(b)

### Practice Exercises

The following lists which questions from the @bird21 practice exercises that are relevant to the statistics component of ENGEN102.

- Practice Exercise 289: Questions 1--4
- Practice Exercise 291: Questions 1--3
- Practice Exercise 293: Questions 1--6
- Practice Exercise 294: Questions 1, 2, 3(a), 3(b), 4, and 5
- Practice Exercise 302: Questions 1--8
- Practice Exercise 304: Questions 1--5
- Practice Exercise 307: Questions 1, 3(a), 5, 6, and 7
- Practice Exercise 308: Questions 5 and 6
- Practice Exercise 309: Questions 1--3  
- Practice Exercise 311: Questions 2, 4, 5, and 6
- Practice Exercise 312: Questions 1, 2, 3, 5, and 6

## Relevant Practice from @stroud13

<!-- Frames have not been processed -->

The following lists which questions from the @stroud13 test exercises and further problems that are relevant to the statistics component of ENGEN102.

- Further Problems 28: Questions 1(b) (i), 1(b) (ii), 2(c), 4, 5, 6(a), 7(b), 8(a), 8(b) (ii), 9(a), and 9(b) (ii)
- Test Exercise 29: Question 6
- Further Problems 29: Questions 17--24

<!-- ## Relevant Practice from @lock21 -->

<!-- Answers and t-multipliers missing from Table B have not been processed -->

<!-- The following lists which questions from the @lock21 exercises that are relevant to the statistics component of ENGEN102 *and* do not require the use of software. -->

<!-- - *6.2-D*: -->
<!--   - Exercises 6.65--6.72 -->
<!--   - Exercises 6.77--6.88 -->
<!-- - *6.2-CI*: -->
<!--   - Exercises 6.89--6.94 -->
<!--   - Exercises 6.99--6.110 -->
<!--   - Exercise 6.117: (a) and (b) -->
<!--   - Exercise 6.119: (a) and (b) -->
<!--   - Exercise 6.120: (a) and (b) -->
<!-- - *6.2-HT*: -->
<!--   - Exercises 6.126--6.140 -->
<!-- - *6.4-D*: -->
<!--   - Exercises 6.198--6.203 -->
<!-- - *6.4-CI*: -->
<!--   - Exercises 6.206--6.212 -->
<!--   - Exercise 6.213: (b) and (c) -->
<!--   - Exercises 6.214--6.220 -->
<!--   - Exercises 6.223 and 6.224 -->
<!-- - *6.4-HT*: -->
<!--   - Exercises 6.227--6.240 -->
<!--   - Exercise 6.241: (a), (b), (c), (e), and (f) -->
<!--   - Exercises 6.242--6.244 -->
<!--   - Exercises 6.246--6.252 -->

## Answers to Relevant Practice from @bird21

The style of these brief solutions follows the same style as @bird21. That is, only the final answer is presented without full working using the methods taught in the statistics component of ENGEN102.

### Answers to Worked Problems

#### *Mean, median, mode and standard deviation*

<ol>
  <li> Mean 5 &emsp; Median 4 &emsp; Mode 3
  <li> Mean &pound;37.20 &emsp; Median &pound;37.19 &emsp; Mode N/A
  <li value="5"> 2.61
</ol>

#### *Probability*

<ol>
  <li> (a\) 20&frasl;53 &emsp; (b\) 33&frasl;53
  <li value="6"> (a\) 0.1
</ol>

#### *The Normal distribution*

1. 492.05 &rightarrow; 492 people
2. 143.85 &rightarrow; 144 people
3. 1.9 &rightarrow; 2 people
4. (a\) 71.25 &rightarrow; 71 bottles &emsp; (b\) 868.2 &rightarrow; 868 bottles &emsp; (c\) 19.8 &rightarrow; 20 bottles &emsp; (d\) 129 bottles

#### *Sampling and estimation theories*

<ol>
  <li value="2"> (a\) *&mu;*~*x&#772;*~ = *&mu;* = 175 cm, &emsp; *&sigma;*~*x&#772;*~ = 1.26 cm
  <li value="9"> (a\) (1.842 cm, 1.858 cm) &emsp; (b\) (1.845 cm, 1.855 cm)
  <li value="11"> (2.145 &Omega;m^-1^, 2.175 &Omega;m^-1^)
</ol>

#### *Significance testing*

<ol>
  <li value="5"> (a\) *t*^\*^~[0.05]{.ch-0}~(*&nu;* = 49) = -\{*t*^\*^~[0.95]{.ch-0}~(*&nu;* = 49)\} = -1.68, *t*~0~ = -2.04  
  Hence the null hypothesis, H~0~: *&mu;* = 75 hours, is rejected in favour of the alternative, H~1~: *&mu;* < 75 hours, at the 5% significance level  
  (b\) *t*^\*^~[0.01]{.ch-0}~(*&nu;* = 49) = -\{*t*^\*^~[0.99]{.ch-0}~(*&nu;* = 49)\} = -2.40, *t*~0~ = -2.04  
  Hence the null hypothesis, H~0~: *&mu;* = 75 hours, is not rejected in favour of the alternative, H~1~: *&mu;* < 75 hours, at the 1% significance level
  <li> (a\) *t*^\*^~[0.9]{.ch-0}~(*&nu;* = 5) = 1.48, *t*~0~ = 1.45  
  Hence the null hypothesis, H~0~: *&mu;* = 18 grams of carbon, is not rejected in favour of the alternative, H~1~: *&mu;* &ne; 18 grams of carbon, at the 20% significance level  
  (b\) *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 5) = 2.02, *t*~0~ = 1.45  
  Hence the null hypothesis, H~0~: *&mu;* = 18 grams of carbon, is not rejected in favour of the alternative, H~1~: *&mu;* &ne; 18 grams of carbon, at the 10% significance level
  <li value="8"> (a\) *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 39) = 2.02, *t*~0~ = -2.49  
  Hence the null hypothesis, H~0~: *&mu;*~1~ &minus; *&mu;*~2~ = 0 ohms, is rejected in favour of the alternative, H~1~: *&mu;*~1~ &minus; *&mu;*~2~ &ne; 0 ohms, at the 5% significance level  
  (b\) *t*^\*^~[0.995]{.ch-0}~(*&nu;* = 39) = 2.71, *t*~0~ = -2.49  
  Hence the null hypothesis, H~0~: *&mu;*~1~ &minus; *&mu;*~2~ = 0 ohms, is not rejected in favour of the alternative, H~1~: *&mu;*~1~ &minus; *&mu;*~2~ &ne; 0 ohms, at the 1% significance level
  <li> *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 5) = 2.02, *t*~0~ = 1.05  
  Hence the null hypothesis, H~0~: *&mu;*~A~ &minus; *&mu;*~B~ = 0 seconds, is not rejected in favour of the alternative, H~1~: *&mu;*~A~ &minus; *&mu;*~B~ &ne; 0 seconds, at the 10% significance level
  <li> Assume *&alpha;* = 0.05  
  *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 5) = 2.57, *t*~0~ = -0.67  
  Hence the null hypothesis, H~0~: *&mu;*~Analyst~ &minus; *&mu;*~Trainee~ = 0 grams, is not rejected in favour of the alternative, H~1~: *&mu;*~Analyst~ &minus; *&mu;*~Trainee~ &ne; 0 grams, at the 5% significance level
</ol>

### Answers to Revision Test Questions

#### Revision Test 18

<ol>
  <li value="3"> (a\) Mean 30 m &emsp; (b\) Median 29 m &emsp; (c\) Mode 28 m &emsp; (d\) Standard deviation 6.18 m
  <li value="6"> (a\) 0.7 &emsp; (c\) 0.7
</ol>

#### Revision Test 19

3. (a\) 210.35 &rightarrow; 210 components &emsp; (b\) 152.5 &rightarrow; 153 components &emsp; (c\) 7.7 &rightarrow; 8 components
4. (a\) 10.56% &emsp; (b\) 0.62% &emsp; (c\) 88.82%

#### Revision Test 20

<ol>
  <li value="2"> (a\) (3.62 cm, 3.68 cm) &emsp; (b\) (3.63 cm, 3.67 cm)
  <li value="4"> (a\) *t*^\*^~[0.05]{.ch-0}~(*&nu;* = 39) = -1.68, *t*~0~ = -2.02  
  Hence the null hypothesis, H~0~: *&mu;* = 260 hours, is rejected in favour of the alternative, H~1~: *&mu;* < 260 hours, at the 5% significance level  
  (b\) *t*^\*^~[0.01]{.ch-0}~(*&nu;* = 39) = -2.43, *t*~0~ = -2.02  
  Hence the null hypothesis, H~0~: *&mu;* = 260 hours, is not rejected in favour of the alternative, H~1~: *&mu;* < 260 hours, at the 1% significance level
  <li> (a\) *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 49) = 2.01, *t*~0~ = -2.07  
  Hence the null hypothesis, H~0~: *&mu;*~1~ &minus; *&mu;*~2~ = 0 cm, is rejected in favour of the alternative, H~1~: *&mu;*~1~ &minus; *&mu;*~2~ &ne; 0 cm, at the 5% significance level  
  (b\) *t*^\*^~[0.995]{.ch-0}~(*&nu;* = 49) = 2.68, *t*~0~ = -2.07  
  Hence the null hypothesis, H~0~: *&mu;*~1~ &minus; *&mu;*~2~ = 0 cm, is not rejected in favour of the alternative, H~1~: *&mu;*~1~ &minus; *&mu;*~2~ &ne; 0 cm, at the 1% significance level
  <li> (a\) *x&#772;* = 50.246 &Omega; &emsp; (b\) *s* = 0.058 &Omega;
</ol>

### Answers to Practice Exercises

#### Practice Exercise 289

1. Mean 7 1&frasl;3, &emsp; Median 8, &emsp; Mode 8
2. Mean 27.25, &emsp; Median 27, &emsp; Mode 26
3. Mean 4.7225, &emsp; Median 4.72, &emsp; Mode 4.72
4. Mean 115.2, &emsp; Median 126.4, &emsp; Mode N/A

#### Practice Exercise 291

1. *s* = 4.97
2. *s* = 3.01 microfarads
3. *x&#772;* = 34.53 megapascals, &emsp; *s* = 0.07737 megapascals

#### Practice Exercise 293

1. Option (d\)
2. Option (a\)
3. Option (b\)
4. Option (c\)
5. Option (d\)
6. Option (b\)

#### Practice Exercise 294

1. (a\) 2&frasl;9 &emsp; (b\) 7&frasl;9
2. (a\) 23&frasl;139 &emsp; (b\) 47&frasl;139 &emsp; (c\) 69&frasl;139
3. (a\) 1&frasl;6 &emsp; (b\) 1&frasl;6
4. 0.7
5. 5&frasl;36

#### Practice Exercise 302

1. 5.67 &rightarrow; 6 components
2. 22.48 &rightarrow; 22 people
3. (a\) 478.65 &rightarrow; 479 tins &emsp; (b\) 62.55 &rightarrow; 63 tins &emsp; (c\) 21.35 &rightarrow; 21 tins
4. 3.57 &rightarrow; 4 components
5. (a\) 130.8 &rightarrow; 131 people &emsp; (b\) 553.2 &rightarrow; 553 people
6. (a\) 15.174 &rightarrow; 15 holes &emsp; (b\) 4.454 &rightarrow; 4 holes
7. (a\) 65 children &emsp; (b\) 208.88 &rightarrow; 209 children &emsp; (c\) 89.08 &rightarrow; 89 children
8. (a\) 1.28 &rightarrow; 1 tablet &emsp; (b\) 85.33 &rightarrow; 85 tablets &emsp; (c\) 13.35 &rightarrow; 13 tablets

#### Practice Exercise 304

1. Option (b\)
2. Option (c\)
3. Option (a\)
4. Option (d\)
5. Option (a\)

#### Practice Exercise 307

<ol>
  <li> *&mu;*~*x&#772;*~ = *&mu;* = 22.4 cm, &emsp; *&sigma;*~*x&#772;*~ = 0.0073 cm
  <li value="3"> (a\) *&mu;*~*x&#772;*~ = *&mu;* = 1.70 cm, &emsp; *&sigma;*~*x&#772;*~ = 2.91 &times; 10^&minus;3^ cm
  <li value="5"> 0.0228
  <li> 0.4972
  <li> 0.0038
</ol>

#### Practice Exercise 308

5. (10.90 tonnes, 11.28 tonnes)
6. &pm; 0.7825 minutes

#### Practice Exercise 309

1. (5.127 MPa, 5.213 MPa)
2. (5.119 MPa, 5.221 MPa)
3. (1.09 &Omega;m^&minus;1^, 1.16 &Omega;m^&minus;1^)

#### Practice Exercise 311

<ol>
  <li value="2"> *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 8) = 1.86, *t*~0~ = 2  
  Hence the null hypothesis, H~0~: *&mu;* = 80%, is rejected in favour of the alternative, H~1~: *&mu;* > 80%, at the 5% significance level
  <li value="4"> *x&#772;* = 10.38 kN, *s* = 0.34 kN  
  *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 19) = 1.73, *t*~0~ = 1.70  
  Hence the null hypothesis, H~0~: *&mu;* = 10.25 kN, is not rejected in favour of the alternative, H~1~: *&mu;* > 10.25 kN, at the 5% significance level
  <li> (a\) *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 9) = 2.26, *t*~0~ = 3.16  
  Hence the null hypothesis, H~0~: *&mu;* = 0.5 cm, is rejected in favour of the alternative, H~1~: *&mu;* &ne; 0.5 cm, at the 5% significance level  
  (b\) *t*^\*^~[0.995]{.ch-0}~(*&nu;* = 9) = 3.25, *t*~0~ = 3.16  
  Hence the null hypothesis, H~0~: *&mu;* = 0.5 cm, is not rejected in favour of the alternative, H~1~: *&mu;* &ne; 0.5 cm, at the 1% significance level
  <li> (a\) *t*^\*^~[0.9]{.ch-0}~(*&nu;* = 5) = 1.48, *t*~0~ = 3.38  
  Hence the null hypothesis, H~0~: *&mu;* = 8000 times, is rejected in favour of the alternative, H~1~: *&mu;* > 8000 times, at the 10% significance level. Therefore the manufacturer's claim can be supported  
  (b\) *t*^\*^~[0.98]{.ch-0}~(*&nu;* = 5) = 2.76, *t*~0~ = 3.38  
  Hence the null hypothesis, H~0~: *&mu;* = 8000 times, is rejected in favour of the alternative, H~1~: *&mu;* > 8000 times, at the 2% significance level. Therefore the manufacturer's claim can be supported
</ol>

#### Practice Exercise 312

<ol>
  <li> *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 79) = 1.66, *t*~0~ = 1.28  
  Hence the null hypothesis, H~0~: *&mu;*~B~ &minus; *&mu;*~A~ = 15 hours, is not rejected in favour of the alternative, H~1~: *&mu;*~B~ &minus; *&mu;*~A~ > 15 hours, at the 5% significance level
  <li> *t*^\*^~[0.975]{.ch-0}~(*&nu;* = 49) = 2.01, *t*~0~ = &minus;2.35  
  Hence the null hypothesis, H~0~: *&mu;*~1~ &minus; *&mu;*~2~ = 0 minutes, is rejected in favour of the alternative, H~1~: *&mu;*~1~ &minus; *&mu;*~2~ &ne; 0 minutes, at the 5% significance level
  <li> *t*^\*^~[0.01]{.ch-0}~(*&nu;* = 4) = -\{*t*^\*^~[0.99]{.ch-0}~(*&nu;* = 4)\} = -3.75, *t*~0~ = -1.32  
  Hence the null hypothesis, H~0~: *&mu;*~1~ &minus; *&mu;*~2~ = 0 &mu;F, is not rejected in favour of the alternative, H~1~: *&mu;*~1~ &minus; *&mu;*~2~ < 0  &mu;F, at the 1% significance level
  <li value="5"> (a\) *t*^\*^~[0.01]{.ch-0}~(*&nu;* = 11) = -\{*t*^\*^~[0.99]{.ch-0}~(*&nu;* = 11)\} = -2.72, *t*~0~ = -1.93  
  Hence the null hypothesis, H~0~: *&mu;*~A~ &minus; *&mu;*~B~ = 0 litres, is not rejected in favour of the alternative, H~1~: *&mu;*~A~ &minus; *&mu;*~B~ < 0 litres, at the 1% significance level  
  (b\) *t*^\*^~[0.05]{.ch-0}~(*&nu;* = 4) = -\{*t*^\*^~[0.95]{.ch-0}~(*&nu;* = 11)\} = -1.80, *t*~0~ = -1.93  
  Hence the null hypothesis, H~0~: *&mu;*~A~ &minus; *&mu;*~B~ = 0 litres, is rejected in favour of the alternative, H~1~: *&mu;*~A~ &minus; *&mu;*~B~ < 0 litres, at the 5% significance level
  <li> *t*^\*^~[0.95]{.ch-0}~(*&nu;* = 4) = 2.13, *t*~0~ = 3.71  
  Hence the null hypothesis, H~0~: *&mu;*~Unleaded~ &minus; *&mu;*~LPG~ = 0 kilometres, is rejected in favour of the alternative, H~1~: *&mu;*~Unleaded~ &minus; *&mu;*~LPG~ > 0 kilometres, at the 5% significance level
</ol>

## Answers to Relevant Practice from @stroud13

### Further Problems 28

<ol>
  <li> (b\) (i\) 76.65 components &emsp; (ii\) 7.748 components
  <li> (c\) (i\) 16.773 mm &emsp; (ii\) 1.360 mm
  <li value="4"> (a\) 2.382 M&ohm; &emsp; (b\) 0.016 M&ohm; &emsp; (c\) 2.38 M&ohm; &emsp; (d\) 2.38 M&ohm;
  <li> (a\) 31.06 kN &emsp; (b\) 0.241 kN &emsp; (c\) 31 kN &emsp; (d\) 31 kN
  <li> (a\) (i\) 11.538 min &emsp; (ii\) 9.728 min &emsp; (iii\) 11.5 min &emsp; (iv\) 11.5 min
  <li> (b\) 1964.4 &rightarrow; 1964 acceptable components
  <li> (a\) (i\) 7.556 kg &emsp; (ii\) 0.127 kg  
  (b\) (ii\) 0.127 kg
  <li> (a\) (i\) 29.638 mm &emsp; (ii\) 0.123 mm  
  (b\) (ii\) 2078.76 &rightarrow; 2079 blocks
</ol>

### Test Exercise 29

<ol>
  <li value="6"> 211.98 &rightarrow; 212 rods
</ol>

### Further Problems 29

17. 0.1271
18. (a\) 0.0078 &emsp; (b\) 0.9028
19. (a\) 0.7492 &emsp; (b\) 0
20. 333.24 &rightarrow; 333 washers
21. (a\) 0.0618 &emsp; (b\) 0.2206
22. (a\) 7.44 &rightarrow; 7 bearings &emsp; (b\) 126.72 &rightarrow; 127 bearings
23. (a\) 0.4835 &emsp; (b\) 0.0146 
24. (a\) 214.8  &rightarrow; 215 bulbs &emsp; (b\) 89.26 % &emsp; (c\) 0
